server:
    # context-path: /myboot 
    session-timeout: 1800
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
    port: 80
    uri-encoding: utf-8
security:
  basic:
    enabled: false
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true    
mybatis: 
  mapper-locations:
  - classpath*:mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.personal.**.domain
mapper:
  mappers:
    - com.personal.common.MyBaseMapper
  not-empty: false
  identity: MYSQL
#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: ehcache